import './globals.css'
import { Inter } from 'next/font/google'

import Image from 'next/image'
import Navbar from '@/components/Navbar'
import Newfooter from '@/components/Newfooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main >
         
            <Navbar />
            {children}
            
            <Newfooter/>
           
          </main>
        </body>
    </html>
  )
}
