"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import React, {useEffect} from "react";
import Navbar from '@/components/Navbar'
import Newfooter from '@/components/Newfooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

    // Disable right-click
    useEffect(() => {
      typeof window !== undefined &&
        window.document.addEventListener("contextmenu", (e) => {
          e.preventDefault();
        });
    }, []);
  
    document.onkeydown = function(e) {
      console.log(e.key)
      if(e.key === 'F12') {
         return false;
      }
      if(e.ctrlKey && e.shiftKey && e.key === 'I') {
         return false;
      }
      if(e.ctrlKey && e.shiftKey && e.key === 'C') {
         return false;
      }
      if(e.ctrlKey && e.shiftKey && e.key === 'J') {
         return false;
      }
      if(e.ctrlKey && e.key === 'u') {
         return false;
      }
    }

  return (
    <html oncontextmenu="return false" lang="en">
      <link rel="icon" href="../Images/favicon.ico"  sizes="64x64"/>
      <body className={inter.className}>
      <main >
         
            <Navbar />
            {children}
            
            <Newfooter/>
           
          </main>
        </body>
    </html>
  )
}
